# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/

default_job = "clippy-all"

[jobs.run-server-standalone-mysql]
command = [
  "cargo",
  "run",
  "--bin",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,mysql,running-from-workspace-root",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run-server-standalone-postgres]
command = [
  "cargo",
  "run",
  "--bin",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,postgres,running-from-workspace-root",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run-server-shuttle]
command = [
  "shuttle",
  "run",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run-client-egui]
command = [
  "cargo",
  "run",
  "--bin",
  "chat-app-client",
  "--all-features",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.run-client-egui-release]
command = [
  "cargo",
  "run",
  "-r",
  "--bin",
  "chat-app-client",
  "--all-features",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"

[jobs.include-ignored]
command = [
  "cargo",
  "test",
  "--",
  "--include-ignored",
]
need_stdout = true
background = false
env.TEST_LOG = "true"

[jobs.test-trace]
command = ["cargo", "test"]
need_stdout = true
env.TEST_LOG = "true"

[jobs.check-wasm-client]
command = [
  "cargo",
  "check",
  "--target",
  "wasm32-unknown-unknown",
  "--package",
  "chat-app-client",
]
need_stdout = false

[jobs.test-chat-server-standalone-mysql]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,mysql",
]
need_stdout = true

[jobs.test-chat-server-standalone-mysql-trace]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,mysql",
]
need_stdout = true
env.TEST_LOG = "true"

# To test Shuttle mode
[jobs.test-chat-server-standalone-pg]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,postgres",
]
need_stdout = true

[jobs.test-chat-server-standalone-pg-trace]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,postgres",
]
need_stdout = true
env.TEST_LOG = "true"

[jobs.check-shuttle]
command = [
  "cargo",
  "check",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "shuttle",
]
need_stdout = false

[jobs.clippy-shuttle]
command = [
  "cargo",
  "clippy",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "shuttle",
]
need_stdout = false

[keybindings]
alt-t = "job:test-trace"
e = "job:run-client-egui"
alt-e = "job:run-client-egui-release"
i = "job:include-ignored"
p = "job:test-chat-server-standalone-pg"
alt-p = "job:test-chat-server-standalone-pg-trace"
r = "job:run-server-standalone-mysql"
alt-r = "job:run-server-standalone-postgres"
ctrl-r = "job:run-server-shuttle"
s = "job:test-chat-server-standalone-mysql"
alt-s = "job:test-chat-server-standalone-mysql-trace"
v = "job:clippy-shuttle"
alt-v = "job:check-shuttle"
w = "job:check-wasm-client"
