# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/

[jobs.run-server-standalone-mysql]
command = [
  "cargo",
  "run",
  "--bin",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,cookie-session,mysql,running-from-workspace-root",
]
allow_warnings = true

[jobs.run-server-standalone-postgres]
command = [
  "cargo",
  "run",
  "--bin",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,cookie-session,postgres,running-from-workspace-root",
]
allow_warnings = true

[jobs.run-server-shuttle]
command = ["shuttle", "run"]
allow_warnings = true
kill = ["pkill", "-TERM", "-P"]

[jobs.run-client-egui]
command = ["cargo", "run", "--bin", "chat-app-client", "--all-features"]
allow_warnings = true

[jobs.run-client-egui-release]
command = ["cargo", "run", "-r", "--bin", "chat-app-client", "--all-features"]
allow_warnings = true

[jobs.include-ignored]
command = ["cargo", "test", "--", "--include-ignored"]
env.TEST_LOG = "true"

[jobs.test-trace]
command = ["cargo", "test"]
env.TEST_LOG = "true"

[jobs.check-wasm-client]
command = [
  "cargo",
  "check",
  "--target",
  "wasm32-unknown-unknown",
  "--package",
  "chat-app-client",
]
env.RUSTFLAGS = '--cfg getrandom_backend="wasm_js"'

[jobs.test-chat-server-standalone-mysql]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,cookie-session,mysql",
]

[jobs.test-chat-server-standalone-mysql-trace]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,cookie-session,mysql",
]
env.TEST_LOG = "true"

[jobs.test-chat-server-standalone-pg]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,cookie-session,postgres",
]

[jobs.test-chat-server-standalone-pg-trace]
command = [
  "cargo",
  "test",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "standalone,cookie-session,postgres",
]
env.TEST_LOG = "true"

[jobs.check-shuttle]
command = [
  "cargo",
  "check",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "shuttle",
]

[jobs.clippy-shuttle]
command = [
  "cargo",
  "clippy",
  "--package",
  "chat-app-server",
  "--no-default-features",
  "--features",
  "shuttle",
]

# TODO 2: Test bacon notification job
[jobs.run_bunyan_notify]
command = [
  "cargo",
  "run",
  "--package",
  "bunyan_log_monitor",
  "--",
  "--test-notification",
  "bacon test notification",
]
need_stdout = true
allow_warnings = true
background = false

[keybindings]
alt-t = "job:test-trace"
e = "job:run-client-egui"
alt-e = "job:run-client-egui-release"
i = "job:include-ignored"
n = "job:run_bunyan_notify"
p = "job:test-chat-server-standalone-pg"
alt-p = "job:test-chat-server-standalone-pg-trace"
r = "job:run-server-standalone-mysql"
alt-r = "job:run-server-standalone-postgres"
ctrl-r = "job:run-server-shuttle"
s = "job:test-chat-server-standalone-mysql"
alt-s = "job:test-chat-server-standalone-mysql-trace"
v = "job:clippy-shuttle"
alt-v = "job:check-shuttle"
w = "job:check-wasm-client"
