[workspace]
resolver = "2"
members = [
  "crates/chat-app-client",
  "crates/chat-app-server",
  "crates/db-types",
  "crates/plugin-chat",
  "crates/switch-db",
  "crates/tracked-cancellations",
  "crates/ws-auth",
  "crates/wykies-client-core",
  "crates/wykies-server",
  "crates/wykies-server-test-helper",
  "crates/wykies-shared",
  "crates/wykies-time",
]

[workspace.dependencies]
# TODO 4: Write a program to check a workspace to see if all dependencies are needed by comparing to Cargo files in member crates
actix-cors = "0.7.0"
actix-files = "0.6.2"
actix-session = "0.10.1"
actix-web = "4.6.0"
actix-ws = "0.3.0"
anyhow = "1.0.94"
argon2 = "0.5.3"
chrono = { version = "0.4.34", default-features = false, features = ["clock", "serde"] }
clap = "4.2.4"
config = { version = "0.15.4", default-features = false, features = ["toml"] }
db-types = { version = "*", path = "crates/db-types", default-features = false }
eframe = "0.30.0"
egui = { version = "0.30.0", default-features = false }
egui_extras = "0.30.0"
ewebsock = "0.8.0"
futures = "0.3.28"
futures-util = "0.3.30"
getrandom = "0.2.15"
insta = "1.40.0"
log = "0.4.22"
plugin-chat = { version = "*", path = "crates/plugin-chat" }
rand = "0.8"
reqwest = { version = "*", default-features = false, features = ["json", "rustls-tls", "cookies"] } # Only to set features, version set by reqwest-cross
reqwest-cross = "0.4.1"
ringbuffer = "0.15.0"
ron = "0.8.1"
rstest = "0.23.0"
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.113"
serde-aux = "4.5.0"
shuttle-runtime = { version = "0.49.0", default-features = false }
shuttle-shared-db = "0.49.0"
sqlx = { version = "0.8.2", default-features = false }
static_assertions = "1.1.0"
strum = "0.26.3"
thiserror = "2.0.9"
tokio = { version = "1.42.0", default-features = false }
tokio-util = "0.7.13"
tracing = "0.1.41"
tracing-actix-web = "0.7.11"
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
tracked-cancellations = { version = "*", path = "crates/tracked-cancellations" }
uuid = "1"
wasm-bindgen-test = "0.3.42"
web-sys = "0.3.72"
web-time = "1.1.0"
ws-auth = { version = "*", path = "crates/ws-auth" }
wykies-client-core = { version = "*", path = "crates/wykies-client-core" }
wykies-server = { version = "*", path = "crates/wykies-server", default-features = false }
wykies-server-test-helper = { version = "*", path = "crates/wykies-server-test-helper" }
wykies-shared = { version = "*", path = "crates/wykies-shared" }
wykies-time = { version = "*", path = "crates/wykies-time" }

[profile.release]
opt-level = 2 # fast and small wasm

# https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html#testing-a-bugfix
[patch.crates-io]
reqwest = { git = "https://github.com/c-git/reqwest.git", branch = "wasm-cookies" }
shuttle-runtime = { git = "https://github.com/shuttle-hq/shuttle" }
