[workspace]
resolver = "2"
members = ["crates/tracked-cancellations", "crates/wykies-time", "crates/wykies-server", "crates/wykies-shared"]

[workspace.dependencies]
# TODO 4: Write a program to check a workspace to see if all dependencies are needed by removing one and seeing if `cargo check` fails
actix-cors = "0.7.0"
actix-files = "0.6.2"
actix-session = "0.10.1"
actix-web = "4.6.0"
actix-ws = "0.3.0"
anyhow = "1.0.94"
chrono = { version = "0.4.39", default-features = false, features = ["clock"] }
config = { version = "0.14", default-features = false, features = ["toml"] }
serde = { version = "1.0.215", features = ["derive"] }
sqlx = { version = "0.8.2", default-features = false }
tokio = { version = "1.42.0", default-features = false }
tokio-util = "0.7.13"
tracing = "0.1.41"
tracing-bunyan-formatter = "0.3.10"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3", features = ["fmt", "json"] }
tracked-cancellations = { version = "*", path = "crates/tracked-cancellations" }
web-time = "1.1.0"
wykies-shared = { version = "*", path = "crates/wykies-shared" }
wykies-time = { version = "*", path = "crates/wykies-time" }
secrecy = { version = "0.10.3", features = ["serde"] }
serde-aux = "4.5.0"
