[workspace]
resolver = "2"
members = ["crates/tracked-cancellations", "crates/wykies-time", "crates/wykies-server", "crates/wykies-middle-end"]

[workspace.dependencies]
chrono = "0.4.38"
serde = { version = "1.0.215", features = ["derive"] }
sqlx = { version = "0.8.2", default-features = false }
tokio = "1.42.0"
tokio-util = "0.7.13"
tracing = "0.1.41"
web-time = "1.1.0"
wykies-time = { version = "*", path = "crates/wykies-time" }
tracked-cancellations = { version = "*", path = "crates/tracked-cancellations" }
