# This section is considered when running `cargo deny check advisories`
# More documentation for the advisories section can be found here:
# https://embarkstudios.github.io/cargo-deny/checks/advisories/cfg.html
[advisories]
ignore = [
  { id = "RUSTSEC-2026-0258", reason = "Will look into it, doesn't seem to be a big issue for us" },
]
