name = "chat-app-demo"

[deploy]
deny_dirty = true
include = [
  ".sqlx/*",
  "crates/chat-app-server/app/*",
  "crates/chat-app-server/configuration/*",
]

[build]
assets = [
  "crates/chat-app-server/app/*",
  "crates/chat-app-server/configuration/*",
]

# Shuttle deployment notes:
# - Do a trunk build in release mode
# - Switch to Shuttle Mode
# - Bump version of server
# - Commit (to prevent dirty and give deployment a name)
