[package]
name = "ws-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web.workspace = true
anyhow.workspace = true
serde.workspace = true
thiserror.workspace = true
wykies-shared.workspace = true
