[package]
name = "wykies-server"
version = "0.1.0"
edition = "2021"
description = "Reusable Server Functionality for an Actix-Web REST server that needs WebSocket Functionality"

[dependencies]
anyhow.workspace = true
config.workspace = true
secrecy.workspace = true
serde.workspace = true
serde-aux.workspace = true
sqlx.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracked-cancellations.workspace = true
wykies-shared.workspace = true
wykies-time.workspace = true

[features]
# TODO 5: Remove MYSQL as default only there for testing
default = ["mysql"] # MySQL is there temporarily
mysql = ["sqlx/mysql"] # Uses MySQL as DB type
