[package]
name = "tracked-cancellations"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["time"] }
tokio-util = { workspace = true }
tracing = { workspace = true }
wykies-time = { workspace = true }
