name: Release Build Confirmation

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_run:
    workflows: [Tests and formatting]
    types: [completed]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  release_compile:
    name: ReleaseCompile
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
      - name: Load sqlx query files for standalone version
        run: cargo run --bin switch-db -- standalone
      - name: Run Release Compile
        run: cargo check --all-features --release
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1