name: Shuttle Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-shuttle-deploy
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      

env:
  CARGO_TERM_COLOR: always
      
jobs:
  # https://docs.github.com/en/actions/sharing-automations/reusing-workflows#calling-a-reusable-workflow
  run_tests:
    uses: ./.github/workflows/general.yml
  deploy:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: wykies/checkout@main
      - uses: wykies/setup-rust-toolchain@main
        with:
          target: wasm32-unknown-unknown        
      - name: Load sqlx query files for shuttle version
        run: cargo run --bin switch-db -- --no-edit-only-copy shuttle
      - name: Install Trunk
        uses: taiki-e/install-action@main
        with:
          tool: trunk
      - name: Build client
        run: ./scripts/build_chat_client.sh
      - name: Include git diff for debug
        run: git diff
      - name: Include git status for debug
        run: git status
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: ${{ secrets.SHUTTLE_PROJ_ID }}